### ISSUE TITLE
rs_map_generator_m.py: TypeError: in method 'from_bool', argument 1 of type 'bool'

### ISSUE THREAD

**Issue by Sout** [kit-cel/gr-lte#24]
Software versions.
gr-lte version 7288cc3
GNU Radio Companion 3.7.11

The Error is as follows.
```
handler caught exception: in method 'from_bool', argument 1 of type 'bool'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gnuradio/gr/gateway.py", line 73, in eval
    try: self._callback(arg)
  File "/usr/lib/python2.7/site-packages/lte/rs_map_generator_m.py", line 64, in handle_msg
    pmt_rs = self.rs_pos_to_pmt(rs_poss)
  File "/usr/lib/python2.7/site-packages/lte/rs_map_generator_m.py", line 88, in rs_pos_to_pmt
    pmt_rs = pmt.list_add(pmt_rs, self.int_list_to_pmt(rs_poss[i + 1]))
  File "/usr/lib/python2.7/site-packages/lte/rs_map_generator_m.py", line 93, in int_list_to_pmt
    return pmt.from_bool(pmt.PMT_F)
  File "/usr/lib/python2.7/site-packages/pmt/pmt_swig.py", line 2269, in from_bool
    return _pmt_swig.from_bool(val)
TypeError: in method 'from_bool', argument 1 of type 'bool'
```
Potential Fix:
The code at rs_map_generator_m.py#L78 should be change to 
```python
return pmt.PMT_F
``` 
or
```python
return ptm.from_bool(False)
```

**Comment by timshandsome** [comment]
The error is following:
handler caught exception: in method 'from_bool', argument 1 of type 'bool'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 73, in eval
    try: self._callback(arg)
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 64, in handle_msg
    pmt_rs = self.rs_pos_to_pmt(rs_poss)
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 88, in rs_pos_to_pmt
    pmt_rs = pmt.list_add(pmt_rs, self.int_list_to_pmt(rs_poss[i + 1]))
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 93, in int_list_to_pmt
    return pmt.from_bool(pmt.PMT_F)
  File "/usr/lib/python2.7/dist-packages/pmt/pmt_swig.py", line 2292, in from_bool
    return _pmt_swig.from_bool(val)
TypeError: in method 'from_bool', argument 1 of type 'bool'
thread[thread-per-block[1]: <block ofdm_estimator_lte_rs_map_generator_m_1 (60)>]: SWIG director method error. Error detected when calling 'feval_p.eval'

handler caught exception: in method 'from_bool', argument 1 of type 'bool'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/gr/gateway.py", line 73, in eval
    try: self._callback(arg)
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 64, in handle_msg
    pmt_rs = self.rs_pos_to_pmt(rs_poss)
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 88, in rs_pos_to_pmt
    pmt_rs = pmt.list_add(pmt_rs, self.int_list_to_pmt(rs_poss[i + 1]))
  File "/usr/local/lib/python2.7/dist-packages/lte/rs_map_generator_m.py", line 93, in int_list_to_pmt
    return pmt.from_bool(pmt.PMT_F)
  File "/usr/lib/python2.7/dist-packages/pmt/pmt_swig.py", line 2292, in from_bool
    return _pmt_swig.from_bool(val)
TypeError: in method 'from_bool', argument 1 of type 'bool'
thread[thread-per-block[0]: <block ofdm_estimator_lte_rs_map_generator_m_0 (61)>]: SWIG director method error. Error detected when calling 'feval_p.eval'

How can I do to resolve them? Please help me, thanks.
