### ISSUE TITLE
Valuesize error: 

### ISSUE THREAD

**Issue by ateckchandani** [kit-cel/gr-lte#9]
Here's a screen shot of the output I get when I execute the 'lte_top_block_siso.grc'  flowchart -- 

Traceback (most recent call last):
  File "/home/security/gr-lte/examples/lte_top_block_siso.py", line 201, in <module>
    main()
  File "/home/security/gr-lte/examples/lte_top_block_siso.py", line 189, in main
    tb = top_block_cls()
  File "/home/security/gr-lte/examples/lte_top_block_siso.py", line 122, in __init__
    self.connect((self.lte_channel_estimator_0, 0), (self.lte_pbch_decoder_0, 0))    
  File "/usr/local/lib64/python2.7/site-packages/gnuradio/gr/hier_block2.py", line 47, in wrapped
    func(self, src, src_port, dst, dst_port)
  File "/usr/local/lib64/python2.7/site-packages/gnuradio/gr/hier_block2.py", line 110, in connect
    self.primitive_connect(*args)
  File "/usr/local/lib64/python2.7/site-packages/gnuradio/gr/runtime_swig.py", line 5304, in primitive_connect
    return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
ValueError: itemsize mismatch: Channel Estimator0:0 using 576, PBCH Decoder0:0 using 4800
INFO: MIB	decoding_rate = -nan

Please help!

**Comment by jarodcs** [comment]
Hi there

Is this the setup that you have for this "lte_top_block_siso.grc" flowchart?
![screenshot from 2017-04-17 03-44-34](https://cloud.githubusercontent.com/assets/6204500/25084081/865a6eb8-230f-11e7-905d-b6f1e4d64cf6.png)

Because from your output, this
 self.connect((self.lte_channel_estimator_0, 0), (self.lte_pbch_decoder_0, 0))
means that the **out0** from Channel Estimator should be connected to **in0** of PBCH Decoder
But from my image is not like that. It is more like the **out0** from Channel Estimator is connected to **in1** of PBCH Decoder

Cheers
Jarodcs

**Comment by mileippert** [comment]
Check the resource blocks settings. Some of the blocks seem to use 6 resource blocks, while the PBCH Decoder uses 50. This change lets the flow graph run on my device.

**Comment by ateckchandani** [comment]
Thanks. I got it figured out.
The Mode of Generation was supposed to be Heir Block mode, not QT GUI.

-

Anisha
